### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by XsidX** [XsidX/recipe_app#9]
> Project link [here](https://github.com/users/XsidX/projects/6/views/1)
> Our collaboration consists of two members: @XsidX and @ChrispaixK 
- Member A: @XsidX 
- Member B: @ChrispaixK

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @XsidX and @ChrispaixK 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
